services:
  - type: web
    name: m3-2-cloud-deploy
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host=0.0.0.0 --port=${PORT}"
    healthCheckPath: /health
    envVars:
      - key: PLATFORM
        value: render
      - key: ADMIN_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
